### ISSUE TITLE
Consistency in raster format export

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#17]
The output files from the trajectory analysis are exported as 2-band rasters, while the land cover change output files are exported as 4 single band files with the name indicating what each one is. I find the second option more useful for the final user. Could we export them all as single band files?

**Comment by azvoleff** [comment]
We'll have to test, which is part of the reason I setup the scripts both ways. Each raster export equals one task on GEE. I think that since GEE queues things by task, the more GEE tasks we have, the longer people may need to wait for their results. And if you have a large number of tasks, I think I have seen on the email list that that will make your tasks lower priority than other users. Can you check on the email list to see what Google recommends? If we really want one file per band we could always export as multiband from GEE and then split into individual files after download.
