### ISSUE TITLE
Change default productivity to from UNCCD to Trends.Earth

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#195]
I think it is time to make the default productivity ours instead of the UNCCD. What do you think?

**Comment by azvoleff** [comment]
Agreed. I am going to wait until after the CRIC for this one, just so nothing changes relative to what folks saw in the trainings, but we do need to get this done sooner rather than later.

We'll need to put a note in the tool and on the webiste or something so people know the default has changed - also in the follow-on project we need to more cleanly attach ensuring that results are reproducible with old versions of the code, but that is another issue.
