### ISSUE TITLE
When uploding a tif. for change in land to Trends.Earth it´s merging the classes. 

### ISSUE THREAD

**Issue by Erickvillacis34** [ConservationInternational/trends.earth#298]
Im using the Trends.Earth program to calculate the 15.3.1 objective from the ODS, but i realize that whe im uploding my own information for the change in land cover with the reclassification needed, the program its sending me a raster tif. with the classification of other land merged with artificial, so in the end im losing the other lands clasification for the interpretation, and the final calculation for the 15.3.1. objetctive it´s giving me 0% information regardind other lands class. 
[Problem Report.docx](https://github.com/ConservationInternational/trends.earth/files/5098528/Problem.Report.docx)

**Comment by azvoleff** [comment]
If I understand correctly you are losing information on the classes that are not within the 7 default IPCC classes, correct? This is by design - right now Trends.Earth supports only the 7 default IPCC classes, and will ignore any codes in your file if they are not reclassed to refer to one of the 7 IPCC classes.

If you are having a different issue let us know and we'll reopen this.
