### ISSUE TITLE
SDg 15.3.1 one step 10 year limit

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#317]
The tool currently prevents analysis with less than an 11 year period (even though the message says 10). Following GPG v2 guidance, we should remove it. Also to facilitate other analysis beyond sdg 15.3.1 reporting.

**Comment by azvoleff** [comment]
@gdaldegan - can you remove this limitation? And @mgroglich - once done, can you verify it is working as expected per the GPGv2?

**Comment by PropeReferio** [comment]
In what file is the 10 year limit? I'd like to work on this.

**Comment by gdaldegan** [comment]
@azvoleff removing the lines below would suffice? Or should I modify the condition threshold itself?
ret = super(DlgCalculateOneStep, self).btn_calculate()
        if not ret:
            return

        if (self.year_final.date().year() - self.year_initial.date().year()) < 10:
            QtWidgets.QMessageBox.critical(None, self.tr("Error"),
                                       self.tr("Initial and final year must be at least 10 years apart."))
            return

        self.close()

**Comment by azvoleff** [comment]
I'd leave the threshold, but instead of "critical", use a "warning" message box, and remove the "return" line. Then you can just give a warning to the user rather than failing if they use less than 10 years of data (by changing the message to say something like: "Initial and final year are less than 10 years apart - note that more reliable results will be given if more data is included in the analysis.").

**Comment by gdaldegan** [comment]
updated the code to throw a warning message instead of not allowing to the calculation to proceed.
