### ISSUE TITLE
Add a name to region of interest

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#368]
Enhance the UI of the settings dialogue in order to allow specifying a name to the Region of Interest (ROI) settings. This name shall be shown on the algorithm execution dialogue in order to remind the user of the current setting.

The user shall not be required to actually input a name of the ROI as this shall be computed dynamically from the current settings. The user is able to override this computed default name in order to supply a more human-friendly name. 

The chosen name must also be saved in `QgsSettings`, together with the other ROI properties.

Examples of computed names:

1. User selects a country and region as the ROI -> `{sluggified-country-name}-{sluggified-region-name}`. Ex: `portugal-setubal`
1. User selects a country and city as the ROI -> `{sluggified-country-name}_{sluggified-city-name}`. Ex: `italy-rome`
1. User selects a point as the ROI -> `pt-lon{longitude}lat{latitude}`. Ex: `pt-lon-19.345lat-22.444
1. User selects a loaded shape as the ROI -> `shape-lon{centroid-longitude}lat{centroid-latitude}`. Ex: `shape-lon21.567-lat-176.123`

#### Notes
- In the examples above, `sluggified` means that the name is modified to be safer to use in file paths, etc. Example: `United Kingdom` becomes `united-kingdom`
- If the user is also using a `buffer` around the ROI, this shall be denoted in the computed name by appending `-buffer-{buffer-length}`. This means that example 1 above would like this instead: `portugal-setubal-buffer-20`

**Comment by azvoleff** [comment]
If there is room in the dialog, I'd suggest there be an option for the user to manually enter a name. While I like automatically generating a name for the region, I worry that for a user using a point or shape to define a region, the lat/lon autogenerated names won't have much meaning - a common current use case is where a national-level policymaker uses the tool to process data for their country, but needs to use their own shapefile to define the national boundary in order to ensure they are using their official country polygon. In that case it would make sense for them to be able to manually enter the country name so they could easily identify the region used.

Or another option could be to use the filename for the region name if the user uses a shape from a file.

**Comment by ricardogsilva** [comment]
@azvoleff 

> I'd suggest there be an option for the user to manually enter a name

Maybe the issue description is not very clear, but that is exactly what we plan to do. We generate a default name automatically and place that in an editable text box. The user is then free to leave the default or modify it to something easier to memorize, if desired.

> Or another option could be to use the filename for the region name if the user uses a shape from a file.
That may be more appropriate as the default name than the current strategy of using the coordinates of the shape's centroid. Lets review after the first implementation to see if it makes sense to use your suggestion instead OK?

**Comment by azvoleff** [comment]
Ah, that makes sense - and waiting until after first implementation to review sounds good
