### ISSUE TITLE
Invalid QgsSettings cause the plugin to not be able to run any algorithm

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#389]
I have somehow managed to save some incorrect state into my `QgsSettings` and now the plugin is unable to run its algorithms. I am attaching a copy of the `.ini` file saved by QGIS in order to help debugging (had to put it inside a zip in order to trick github).

If I try to run a TE algorithm with these QSettings in place my QGIS just freezes and I eventually am forced to kill it.

When a new QGIS profile is used, one with also a new QgsSettings object, the algorithm execution error does not manifest - If I start a new QGIS profile, install TE into it and try to run an algorithm, execution fails in a wel behaved manner, showing me a pop up dialogue with the following message:

```
Choose an area of interest.
```

So it seems that the original `QgsSettings` have some error in the Trends.Earth region of interest.

QGIS settings file: [qgis-settings-ini.zip](https://github.com/ConservationInternational/trends.earth/files/6310150/qgis-settings-ini.zip)

**Comment by luipir** [comment]
I'm able to replicate using the provided qgis.ini

**Comment by luipir** [comment]
hangs into this line: https://github.com/ConservationInternational/trends.earth/blob/decision-trees/LDMP/calculate.py#L909

**Comment by luipir** [comment]
the problem is that the result of:
https://github.com/ConservationInternational/trends.earth/blob/decision-trees/LDMP/calculate.py#L910 is not casted to Bool => return 'false? => ttry to do transformation entering in infitite while in https://github.com/ConservationInternational/trends.earth/blob/decision-trees/LDMP/calculate.py#L106

it's not the only problem I found when Qsetting.getValue is not correctly cast (toBool or toInt)
