### ISSUE TITLE
"Open layouts" button on reports tool not working

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#593]
There is a "Open layouts" button for the reports button now accompanying each dataset:

![image](https://user-images.githubusercontent.com/107753/160455917-7df68cd1-6223-43ae-8a11-b21ef6695330.png)

Which I click it however, nothing seems to happen. Can you look at this @gkahiu?

**Comment by gkahiu** [comment]
Could you **Open report directory** and check whether there is a file with a _qgz_ extension? If present, does it have a QGIS icon associated with it? Can you try to open it by double clicking?

**Comment by azvoleff** [comment]
Yes, the .qgz file is there, but you are right - the problem is there is no file association for it. Is it possible to associate the qgz file with QGIS during the plugin installation? Or else can we pass the correct qgis executable path to the **open report directory** function directly?

**Comment by azvoleff** [comment]
Actually one note @gkahiu - the open layout button works but on load I get:

![image](https://user-images.githubusercontent.com/107753/161836813-963f13dc-97b1-41a1-90a3-5e4537a25389.png)

"Auto-find" works, so I can still load. Then on load I get:

![image](https://user-images.githubusercontent.com/107753/161836890-b5af93bf-9a78-4a11-a4c5-570a2befb8ec.png)

Is there any way to automate these steps so the user doesn't need them every time?

**Comment by gkahiu** [comment]
Thanks @azvoleff for the feedback. See my responses below:

> Actually one note @gkahiu - the open layout button works but on load I get:
> 
> ![image](https://user-images.githubusercontent.com/107753/161836813-963f13dc-97b1-41a1-90a3-5e4537a25389.png)

This issue is caused when the (relative) path to one or more datasets has been changed. In your case, it seems the folder for basemap layers might have been moved after the qgz file had been created. As the base layers are in the plugin folder, might you have moved your plugin folder from the time this project was created? To confirm, could you delete the **reports** folder for this specific dataset then refresh the **Datasets** window so that the reports are generated afresh, after which try **Open layouts...** to see if you encounter the same issue of broken paths to the datasets. 

If it still persists then I can set the project to use absolute data paths. 

In production, we are assuming the path to the plugin directory will be fixed after (plugin) installation hence users should not encounter this issue.
 
> "Auto-find" works, so I can still load. Then on load I get:
> 
> ![image](https://user-images.githubusercontent.com/107753/161836890-b5af93bf-9a78-4a11-a4c5-570a2befb8ec.png)

Does this occur when you click on **Show** or **Create**? 

![Layout_manager](https://user-images.githubusercontent.com/3840267/161906534-5972514b-bdbc-4a67-9913-779aa7192af5.png)

> Is there any way to automate these steps so the user doesn't need them every time?

**Comment by azvoleff** [comment]
Thanks @gkahiu.

> This issue is caused when the (relative) path to one or more datasets has been changed. In your case, it seems the folder for basemap layers might have been moved after the qgz file had been created. As the base layers are in the plugin folder, might you have moved your plugin folder from the time this project was created?

No, I didn't change the location of the plugin or data folder

> To confirm, could you delete the reports folder for this specific dataset then refresh the Datasets window so that the reports are generated afresh, after which try Open layouts... to see if you encounter the same issue of broken paths to the datasets.

Yes, it still shows up.

As to the second issue I mentioned above (re the print layout title), it no longer appears (possible I'd accidentally hit create, sorry!).

**Comment by gkahiu** [comment]
I have a possible fix  in a9ecf03da0a9400c8eaf45d179dc1730b11b4950 to use absolute data paths in the reports' project. Let me know if this resolves the issue.

**Comment by azvoleff** [comment]
Yes - that fixes it. Thanks!
