### ISSUE TITLE
:book: We need to automate the publishing of documentation changes

### ISSUE THREAD

**Issue by timlinux** [ConservationInternational/trends.earth#613]
Using github actions to build and push straight to RTD

**Comment by timlinux** [comment]
https://github.com/ammaraskar/sphinx-action

**Comment by gkahiu** [comment]
@azvoleff I noticed there is already an existing integration in RTD - [https://trendsearth.readthedocs.io/en/latest/](https://trendsearth.readthedocs.io/en/latest/) - though with some build issues.

Is it possible to get admin access to the dashboard?

**Comment by timlinux** [comment]
@azvoleff to check on RTD for us please

**Comment by gkahiu** [comment]
The build is now passing, see a temporary link [here](https://trendsearth--647.org.readthedocs.build/en/647/). I have set `develop` as the _latest_ branch but you can also modify to any other branch. Once you release, then you can specify the tag for the _stable_ version.

I have enabled the `Build pull requests for this project` option for testing purposes, otherwise please feel free to disable it. 

Finally, image file extensions for the docs should be in lowercase otherwise the VM will complain of not finding the files. I have added an Invoke task to convert _PNG_ extensions to _png_ but it will be preferable if future image additions in the documentation have their file extensions in lowercase.

**Comment by azvoleff** [comment]
Thanks John! Looks fine to me, but @MLNoon and @gabrieldaldegan can you check here https://trendsearth.readthedocs.io/en/latest/ and let us know if you see any issues? That page should have the latest development version of the docs.
