### ISSUE TITLE
Internal enhancements and improvements: Reconfigure the current implementation of high-resolution land cover data processing workflow 

### ISSUE THREAD

**Issue by amyburness** [ConservationInternational/trends.earth#816]
Reconfigure the current implementation of high-resolution land cover data processing workflow based on  engagement with users. A fractional cover type approach would be better than current resampling of all data to the finest resolution. This will decrease processing times significantly when using HR land cover data.

**Comment by amyburness** [comment]
Notes from Meetings: 
When a user brings their own data into the plugin we need to change the resampiling to the more efficient geoprossessing fractional cover type. We also need to test that fractional cover is indeed more efficient. 

Notes to read on fractional cover :
https://www.digitalearthafrica.org/platform-resources/services/fractional-cover

**Comment by gdaldegan** [comment]
Back a couple of months ago Amy said she would consult a colleague with Kartoza to check whether it would be advantageous to implement the fractional cover algorithm in order to speed up ingestion of local datasets, which normally features finer spatial resolution that the default datasets. Do we have a position there?

**Comment by mvmaltitz** [comment]
Based on the transcript, here’s a technical breakdown of what needs to be done for Option 2:

---

### Option 2: Byte-based Fractional Cover Rasters per Class

**Goal:** Resample finer-resolution raster data to a coarser resolution, storing fractional cover values as byte-based rasters, one per land cover class.

---

### Step-by-Step Implementation:

1. **Resampling to Coarser Resolution:**
   - Aggregate finer-resolution data (e.g., 10m) to a coarser resolution (e.g., 100m).
   - For each coarse-resolution pixel, calculate the percentage coverage of each land cover class within that area.

2. **Class-Specific Rasters:**
   - For N land cover classes, create N rasters — one per class.
   - Each raster contains byte values (0–100) representing the percentage (rounded to the nearest whole number) of that class in the coarse pixel.

3. **Byte Encoding:**
   - Store each raster using an 8-bit unsigned integer (uint8).
   - Each cell value represents a percentage (e.g., 0 = 0%, 100 = 100%).

4. **Rounding Logic:**
   - Round calculated percentages to the nearest integer.
   - Be aware that due to rounding, percentages across rasters for a given pixel may not sum exactly to 100%.

5. **Compression Optimization:**
   - Take advantage of repeated values across the raster for compression (e.g., run-length encoding).
   - Storing as bytes rather than floats enables better compression and reduced storage.

6. **Optional – Use Floats for Accuracy:**
   - If exact fractional totals are required (e.g., summing to exactly 100%), use float32 or float64 per raster instead.
   - This will increase file size and reduce compressibility.

---

### Additional Enhancements:

- Within the import tool:
  - Estimate and display the potential space savings of using the byte-per-class raster method versus a single float raster with all classes.
  - Use known input and output resolutions and number of classes to provide a comparative storage estimate.
